param1: 
  type: "list"
  value: 
    - "127.0.0.1"
param2: 
  type: "choice"
  value:
    - 80
    - 443

param3: 
  type: "single"
  value: 1000

param4:
  type: "single"
  value: "Google Chrome"


test:
  type: "list"
  value:
    - 123
    - 465
    - 563